-- Align legacy "properties" table to current PropertyEntity shape.
-- Idempotent for environments where older Flyway scripts already ran.

ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS owner_id VARCHAR(36);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS name_vi VARCHAR(255);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS name_en VARCHAR(255);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS property_type VARCHAR(100);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(50);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS province_code VARCHAR(20);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS district_code VARCHAR(20);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS ward_code VARCHAR(20);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS address_detail_vi VARCHAR(500);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS address_detail_en VARCHAR(500);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS logo TEXT;
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS logo_alt_vi VARCHAR(255);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS logo_alt_en VARCHAR(255);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS description_vi TEXT;
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS description_en TEXT;
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS rejection_note TEXT;
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS approved_by VARCHAR(36);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS schedule_buffer_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS schedule_is_over_day BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
ALTER TABLE IF EXISTS properties ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();
